language: scala
sudo: false
jdk:
- oraclejdk8
dist: trusty
env:
  global:
  - TRAVIS_SBT_VERSION="1.3.7"
  - SBT_OPTS="-Dsbt.color=true -Dsbt.supershell=false"
script:
- sbt coverage test coverageReport
after_success:
- sbt coveralls
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
